### ISSUE TITLE
Transferring the work to heads

### ISSUE THREAD

**Issue by amil-rp-work** [imjal/MetaPix#2]
Hey @imjal 
Thanks for sharing such an awesome work.
I was wondering if similar to pose, we can use your work and facial landmarks as a way to do face swapping in videos?

**Comment by imjal** [comment]
Hi! Thank you for your interest! That should be doable, I would suggest localizing the facial landmarks off the shelf, and then pass it into the network and adjust the input channels of Pix2PixHD.
